### ISSUE TITLE
Create architecture diagrams for IdentityWallet configurations

### ISSUE THREAD

**Issue by michaelsena** [3box/identity-wallet-js#4]
We likely need a few diagrams that include the various modules and components, including: device/browser, third-party app, wallet, web3.js, eth rpc, 3id rpc, IdentityWallet SDK, 3Box.js SDK

Without IdentityWallet:
- [ ] Current situation for web apps

With IdentityWallet:
- [ ] New situation for web apps
- [ ] New situation for mobile wallets interacting with a web app
- ... any more?

**Comment by michaelsena** [comment]
Once you create these, I can add them to the blog post and publish the announcement.

**Comment by oed** [comment]
Here is the first draft @michaelsena https://www.notion.so/threebox/Introducing-IdentityWallet-SDK-c3a80eb675d6482aa4fd062ba976a2c9

Might need some tweaks based on your input :)

**Comment by michaelsena** [comment]
I added a new version of these to the docs site draft. Could use your input!

**Comment by oed** [comment]
Looks good. Two things:
* Maybe change IDW SDK to 3IDProvider in the last two
* The first one will likely change with v1 of IDW, e.g. ethProvider will no longer be needed.

**Comment by michaelsena** [comment]
Why is it 3ID provider in the last 2 and not the first as well? @oed

**Comment by oed** [comment]
Because we're passing the IdentityWallet directly. In the v1.0 we'll likely have a method like `idWallet.get3idProvider()`. Basically we'll have a better separation between the two things. For now I think it makes sense to just have it as IdentityWallet though.

Oh, now I see. Sorry should have more clear before. The left hand side of the last two should be 3IDProvider and the right hand side should still be IdentityWallet SDK.
